title: <p align="left"> Luka Negoita, PhD </p>

logo: "/images/profile.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/Negoita-March-2022.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/negoita/">LinkedIn</a> |
  <a href="https://github.com/lukaneg">GitHub</a>
  </p>
  
  <p align="justify">
  Hi, I'm Luka and I'm a Data Scientist and Ecologist. My portfolio includes some of the projects I've recently worked on, with a strong emphasis on business impact and biodiversity conservation.
  </p>
  
    <p align="left">
    <i></i>
    I also run an online school where I teach <a href="https://www.rforecology.com">R for Ecology</a> :)
    </p>
  
  <p align="center">
  <i>I believe the fundamental beauty of the world lies in the mechanisms behind the patterns that we see.</i>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-145578661-1 # Google Analytics tracking ID
