title: <p align="left"> Luka Negoita, PhD </p>

logo: "/images/profile.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/Negoita_resume_08_07_20.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/negoita/">LinkedIn</a> |
  <a href="https://github.com/lukaneg">GitHub</a>
  </p>
  
  <p align="center">
  <a href="https://www.rforecology.com">I teach R for Ecology</a>
  </p>
  
  <p align="justify">
  I believe the fundamental beauty of the world lies in the stories behind the patterns we see.
  <br><br>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-145578661-1 # Google Analytics tracking ID
