title: <p align="left"> Luka Negoita, PhD </p>

logo: "/images/portrait2_bw.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Luka-Negoita-Resume-Nov-2024.pdf" target="_blank">Resume</a> |
  <a href="https://www.linkedin.com/in/negoita/" target="_blank">LinkedIn</a> |
  <a href="https://github.com/lukaneg" target="_blank">GitHub</a>
  </p>
  
  <p align="justify">
  Hi, I'm Luka and I'm a Data Scientist. My portfolio includes some of the projects I've worked on, with a strong emphasis on actionable insights, research, and biodiversity conservation.
  </b>
  <a href="pdf/Luka-Negoita-Resume-Nov-2024.pdf" target="_blank">Click here to see my resume</a> 
  </p>
  
    <p align="left">
    <i></i>
    I also run an online school where I teach <a href="https://www.rforecology.com">R for Ecology</a> :)
    </p>
  
theme: jekyll-theme-minimal


# google_analytics: UA-145578661-1 # Google Analytics tracking ID
